// IMPORTANT: THIS FILE IS AUTO GENERATED BY bin/version.js - DO NOT MANUALLY EDIT OR CHECKIN!
const VERSION = {
    "dirty": true,
    "raw": "bb6abf5-dirty",
    "hash": "bb6abf5",
    "distance": null,
    "tag": null,
    "semver": null,
    "suffix": "bb6abf5-dirty",
    "semverString": null,
    "version": "0.1.0"
};

module.exports = VERSION;
